package temperatus.model.pojo;
// Generated 08-dic-2015 14:25:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Button generated by hbm2java
 */
@Entity
@Table(name = "BUTTON", schema = "PUBLIC", catalog = "DATABASE")
public class Button implements java.io.Serializable {

	private Integer id;
	private Ibutton ibutton;
	private Position position;
	private Test test;

	public Button() {
	}

	public Button(Ibutton ibutton, Position position, Test test) {
		this.ibutton = ibutton;
		this.position = position;
		this.test = test;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IBUTTON_ID")
	public Ibutton getIbutton() {
		return this.ibutton;
	}

	public void setIbutton(Ibutton ibutton) {
		this.ibutton = ibutton;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POSITION_ID")
	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEST_ID")
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

}
