package temperatus.model.pojo;
// Generated 08-dic-2015 14:25:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Data generated by hbm2java
 */
@Entity
@Table(name = "DATA", schema = "PUBLIC", catalog = "DATABASE")
public class Data implements java.io.Serializable {

	private Integer id;
	private Button button;
	private Date date;
	private String data;

	public Data() {
	}

	public Data(Button button, Date date, String data) {
		this.button = button;
		this.date = date;
		this.data = data;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BUTTON_ID")
	public Button getButton() {
		return this.button;
	}

	public void setButton(Button button) {
		this.button = button;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", length = 8)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "DATA")
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
