package temperatus.model.pojo;

import javafx.beans.property.SimpleStringProperty;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Formula generated by hbm2java
 */
@Entity
@Table(name = "FORMULA", schema = "PUBLIC", catalog = "DATABASE", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class Formula implements java.io.Serializable {

    private Integer id;
    private SimpleStringProperty name = new SimpleStringProperty();
    private SimpleStringProperty description = new SimpleStringProperty();
    private SimpleStringProperty reference = new SimpleStringProperty();
    private SimpleStringProperty operation = new SimpleStringProperty();

    public Formula() {
    }

    public Formula(String name, String operation) {
        this.name.setValue(name);
        this.operation.setValue(operation);
    }

    public Formula(String name, String description, String reference, String operation) {
        this.name.setValue(name);
        this.description.setValue(description);
        this.reference.setValue(reference);
        this.operation.setValue(operation);
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "NAME", unique = true, nullable = false, length = 50)
    public String getName() {
        return this.name.getValue();
    }

    public void setName(String name) {
        this.name.setValue(name);
    }

    @Column(name = "DESCRIPTION", length = 200)
    public String getDescription() {
        return this.description.getValue();
    }

    public void setDescription(String description) {
        this.description.setValue(description);
    }

    @Column(name = "REFERENCE", length = 200)
    public String getReference() {
        return this.reference.getValue();
    }

    public void setReference(String reference) {
        this.reference.setValue(reference);
    }

    @Column(name = "OPERATION", nullable = false, length = 200)
    public String getOperation() {
        return this.operation.getValue();
    }

    public void setOperation(String operation) {
        this.operation.setValue(operation);
    }

    @Override
    public String toString() {
        return this.name.getValue();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Formula)) return false;

        Formula formula = (Formula) o;

        if (getName() != null ? !getName().equals(formula.getName()) : formula.getName() != null) return false;
        return !(getOperation() != null ? !getOperation().equals(formula.getOperation()) : formula.getOperation() != null);

    }

    @Override
    public int hashCode() {
        int result = getName() != null ? getName().hashCode() : 0;
        result = 31 * result + (getOperation() != null ? getOperation().hashCode() : 0);
        return result;
    }

    @Transient
    public SimpleStringProperty getNameProperty() {
        return name;
    }

    @Transient
    public SimpleStringProperty getReferenceProperty() {
        return reference;
    }

    @Transient
    public SimpleStringProperty getOperationProperty() {
        return operation;
    }
}
