package temperatus.model.pojo;
// Generated 08-dic-2015 14:25:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * GamePosition generated by hbm2java
 */
@Entity
@Table(name = "GAME_POSITION", schema = "PUBLIC", catalog = "DATABASE")
public class GamePosition implements java.io.Serializable {

	private Integer id;
	private Game game;
	private Position position;

	public GamePosition() {
	}

	public GamePosition(Game game, Position position) {
		this.game = game;
		this.position = position;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GAME_ID")
	public Game getGame() {
		return this.game;
	}

	public void setGame(Game game) {
		this.game = game;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POSITION_ID")
	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

}
