package temperatus.model.pojo;
// Generated 07-feb-2016 23:59:41 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * GameFormula generated by hbm2java
 */
@Entity
@Table(name = "GAME_FORMULA", schema = "PUBLIC", catalog = "DATABASE")
public class GameFormula implements java.io.Serializable {

	private Integer id;
	private Integer formulaId;
	private Integer gameId;

	public GameFormula() {
	}

	public GameFormula(Integer formulaId, Integer gameId) {
		this.formulaId = formulaId;
		this.gameId = gameId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "GAME_ID", unique = true, nullable = false)
	public Integer getGameId() {
		return gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

	@Column(name = "FORMULA_ID", unique = true, nullable = false)
	public Integer getFormulaId() {
		return formulaId;
	}

	public void setFormulaId(Integer formulaId) {
		this.formulaId = formulaId;
	}

}
