package temperatus.model.pojo;// default package
// Generated Feb 4, 2017 1:16:26 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GamePositionId generated by hbm2java
 */
@Embeddable
public class GamePositionId implements java.io.Serializable {

	private int gameId;
	private int positionId;

	public GamePositionId() {
	}

	public GamePositionId(int gameId, int positionId) {
		this.gameId = gameId;
		this.positionId = positionId;
	}

	@Column(name = "GAME_ID", nullable = false)
	public int getGameId() {
		return this.gameId;
	}

	public void setGameId(int gameId) {
		this.gameId = gameId;
	}

	@Column(name = "POSITION_ID", nullable = false)
	public int getPositionId() {
		return this.positionId;
	}

	public void setPositionId(int positionId) {
		this.positionId = positionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GamePositionId))
			return false;
		GamePositionId castOther = (GamePositionId) other;

		return (this.getGameId() == castOther.getGameId()) && (this.getPositionId() == castOther.getPositionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGameId();
		result = 37 * result + this.getPositionId();
		return result;
	}

}
