package temperatus.model.pojo;// default package
// Generated Feb 4, 2017 1:16:26 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.*;

/**
 * GamePosition generated by hbm2java
 */
@Entity
@Table(name = "GAME_POSITION", schema = "PUBLIC", catalog = "DATABASE")
public class GamePosition implements java.io.Serializable {

	private GamePositionId id;
	private Game game;
	private Position position;
	private Integer ordering;

	public GamePosition() {
	}

	public GamePosition(GamePositionId id, Game game, Position position) {
		this.id = id;
		this.game = game;
		this.position = position;
	}

	public GamePosition(GamePositionId id, Game game, Position position, Integer ordering) {
		this.id = id;
		this.game = game;
		this.position = position;
		this.ordering = ordering;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "gameId", column = @Column(name = "GAME_ID", nullable = false)),
			@AttributeOverride(name = "positionId", column = @Column(name = "POSITION_ID", nullable = false)) })
	public GamePositionId getId() {
		return this.id;
	}

	public void setId(GamePositionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GAME_ID", nullable = false, insertable = false, updatable = false)
	public Game getGame() {
		return this.game;
	}

	public void setGame(Game game) {
		this.game = game;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POSITION_ID", nullable = false, insertable = false, updatable = false)
	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	@Column(name = "ORDERING")
	public Integer getOrdering() {
		return this.ordering;
	}

	public void setOrdering(Integer ordering) {
		this.ordering = ordering;
	}

}
