package temperatus.model.pojo;
// Generated 09-feb-2016 22:15:19 by Hibernate Tools 4.3.1.Final

import javafx.beans.property.SimpleStringProperty;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Game generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "GAME", schema = "PUBLIC", catalog = "DATABASE", uniqueConstraints = {@UniqueConstraint(columnNames = "TITLE"), @UniqueConstraint(columnNames = "ID")})
public class Game implements java.io.Serializable {

    private Integer id;
    private String title;
    private int numButtons;
    private String observations;
    private Set<Formula> formulas = new HashSet<Formula>(0);
    private Set<Position> positions = new HashSet<Position>(0);

    public Game() {
    }

    public Game(String title, int numButtons) {
        this.title = title;
        this.numButtons = numButtons;
    }

    public Game(String title, int numButtons, String observations) {
        this.title = title;
        this.numButtons = numButtons;
        this.observations = observations;
    }

    public Game(String title, int numButtons, String observations, Set<Formula> formulas, Set<Position> positions) {
        this.title = title;
        this.numButtons = numButtons;
        this.observations = observations;
        this.formulas = formulas;
        this.positions = positions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "TITLE", unique = true, nullable = false, length = 100)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "NUM_BUTTONS", nullable = false)
    public int getNumButtons() {
        return this.numButtons;
    }

    public void setNumButtons(int numButtons) {
        this.numButtons = numButtons;
    }

    @Column(name = "OBSERVATIONS")
    public String getObservations() {
        return this.observations;
    }

    public void setObservations(String observations) {
        this.observations = observations;
    }

    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
    @JoinTable(name = "GAME_FORMULA", schema = "PUBLIC", catalog = "DATABASE", joinColumns = {
            @JoinColumn(name = "GAME_ID", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "FORMULA_ID", nullable = false, updatable = false)})
    public Set<Formula> getFormulas() {
        return this.formulas;
    }

    public void setFormulas(Set<Formula> formulas) {
        this.formulas = formulas;
    }

    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
    @JoinTable(name = "GAME_POSITION", schema = "PUBLIC", catalog = "DATABASE", joinColumns = {
            @JoinColumn(name = "GAME_ID", referencedColumnName = "ID", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "POSITION_ID", referencedColumnName = "ID", nullable = false, updatable = false)})
    public Set<Position> getPositions() {
        return this.positions;
    }

    public void setPositions(Set<Position> positions) {
        this.positions = positions;
    }

    @Override
    public String toString() {
        return title;
    }

    @Transient
    public SimpleStringProperty getTitleProperty() {
        return new SimpleStringProperty(title);
    }

    @Transient
    public SimpleStringProperty getNumberOfButtonsProperty() {
        return new SimpleStringProperty(String.valueOf(numButtons));
    }

    @Transient
    public SimpleStringProperty getNumberOfDefaultPositionsProperty() {
        return new SimpleStringProperty(String.valueOf(getPositions().size()));
    }

    @Transient
    public SimpleStringProperty getNumberOfDefaultFormulasProperty() {
        return new SimpleStringProperty(String.valueOf(getFormulas().size()));
    }

}
