package temperatus.model.pojo;
// Generated Apr 13, 2016 9:55:24 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "IMAGE", schema = "PUBLIC", catalog = "DATABASE")
public class Image implements java.io.Serializable {

    private Integer id;
    private Game game;
    private String path;

    public Image() {
    }

    public Image(Game game, String path) {
        this.game = game;
        this.path = path;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GAME_ID", nullable = false)
    public Game getGame() {
        return this.game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    @Column(name = "PATH", nullable = false)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
