package temperatus.model.pojo;
// Generated 20-ene-2016 21:22:04 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Mision generated by hbm2java
 */
@Entity
@Table(name = "MISION", schema = "PUBLIC", catalog = "DATABASE")
public class Mision implements java.io.Serializable {

	private Integer id;
	private Project project;
	private Subject subject;
	private String name;
	private String author;
	private Date dateIni;
	private String observations;
	private Integer gameId;

	public Mision() {
	}

	public Mision(String author) {
		this.author = author;
	}

	public Mision(Project project, Subject subject, String name, String author, Date dateIni, String observations,
			Integer gameId) {
		this.project = project;
		this.subject = subject;
		this.name = name;
		this.author = author;
		this.dateIni = dateIni;
		this.observations = observations;
		this.gameId = gameId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBJECT_ID")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "AUTHOR", nullable = false, length = 30)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_INI", length = 8)
	public Date getDateIni() {
		return this.dateIni;
	}

	public void setDateIni(Date dateIni) {
		this.dateIni = dateIni;
	}

	@Column(name = "OBSERVATIONS")
	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	@Column(name = "GAME_ID")
	public Integer getGameId() {
		return this.gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

}
