package temperatus.model.pojo;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Mission generated by hbm2java
 */
@Entity
@Table(name = "MISSION", schema = "PUBLIC", catalog = "DATABASE", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class Mission implements java.io.Serializable {

    private Integer id;
    private Author author;
    private Game game;
    private Project project;
    private Subject subject;
    private String name;
    private Date dateIni;
    private String observations;
    private Set<Record> records = new HashSet<Record>(0);

    public Mission() {
    }

    public Mission(Author author, Game game, Project project, Subject subject, String name, Date dateIni) {
        this.author = author;
        this.game = game;
        this.project = project;
        this.subject = subject;
        this.name = name;
        this.dateIni = dateIni;
    }

    public Mission(Author author, Game game, Project project, Subject subject, String name, Date dateIni,
                   String observations, Set<Record> records) {
        this.author = author;
        this.game = game;
        this.project = project;
        this.subject = subject;
        this.name = name;
        this.dateIni = dateIni;
        this.observations = observations;
        this.records = records;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
    @JoinColumn(name = "AUTHOR_ID", nullable = false)
    public Author getAuthor() {
        return this.author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
    @JoinColumn(name = "GAME_ID", nullable = false)
    public Game getGame() {
        return this.game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
    @JoinColumn(name = "PROJECT_ID", nullable = false)
    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
    @JoinColumn(name = "SUBJECT_ID", nullable = false)
    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    @Column(name = "NAME", unique = true, nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_INI", nullable = false, length = 8)
    public Date getDateIni() {
        return this.dateIni;
    }

    public void setDateIni(Date dateIni) {
        this.dateIni = dateIni;
    }

    @Column(name = "OBSERVATIONS")
    public String getObservations() {
        return this.observations;
    }

    public void setObservations(String observations) {
        this.observations = observations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mission", cascade = CascadeType.ALL)
    public Set<Record> getRecords() {
        return this.records;
    }

    public void setRecords(Set<Record> records) {
        this.records = records;
    }

    @Override
    public String toString() {
        return "Mission{" +
                "name='" + name + '\'' +
                ", dateIni=" + dateIni +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Mission mission = (Mission) o;

        if (id != null ? !id.equals(mission.id) : mission.id != null) return false;
        if (author != null ? !author.equals(mission.author) : mission.author != null) return false;
        if (game != null ? !game.equals(mission.game) : mission.game != null) return false;
        if (project != null ? !project.equals(mission.project) : mission.project != null) return false;
        if (subject != null ? !subject.equals(mission.subject) : mission.subject != null) return false;
        if (name != null ? !name.equals(mission.name) : mission.name != null) return false;
        if (dateIni != null ? !dateIni.equals(mission.dateIni) : mission.dateIni != null) return false;
        if (observations != null ? !observations.equals(mission.observations) : mission.observations != null)
            return false;
        return !(records != null ? !records.equals(mission.records) : mission.records != null);

    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (author != null ? author.hashCode() : 0);
        result = 31 * result + (game != null ? game.hashCode() : 0);
        result = 31 * result + (project != null ? project.hashCode() : 0);
        result = 31 * result + (subject != null ? subject.hashCode() : 0);
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (dateIni != null ? dateIni.hashCode() : 0);
        result = 31 * result + (observations != null ? observations.hashCode() : 0);
        result = 31 * result + (records != null ? records.hashCode() : 0);
        return result;
    }
}
