package temperatus.model.pojo;
// Generated 20-ene-2016 21:22:04 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Mission generated by hbm2java
 */
@Entity
@Table(name = "MISSION", schema = "PUBLIC", catalog = "DATABASE")
public class Mission implements java.io.Serializable {

    private Integer id;
    private String name;
    private String author;
    private Date dateIni;
    private String observations;
    private Integer gameId;
    private Integer projectId;
    private Integer subjectId;

    public Mission() {
    }

    public Mission(String author) {
        this.author = author;
    }

    public Mission(String name, String author, Date dateIni, String observations,
                   Integer gameId, Integer projectId, Integer subjectId) {
        this.name = name;
        this.author = author;
        this.dateIni = dateIni;
        this.observations = observations;
        this.gameId = gameId;
        this.projectId = projectId;
        this.subjectId = subjectId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "NAME", length = 100, unique = true, nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "AUTHOR", nullable = false, length = 30)
    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_INI", length = 8, nullable = false)
    public Date getDateIni() {
        return this.dateIni;
    }

    public void setDateIni(Date dateIni) {
        this.dateIni = dateIni;
    }

    @Column(name = "OBSERVATIONS")
    public String getObservations() {
        return this.observations;
    }

    public void setObservations(String observations) {
        this.observations = observations;
    }

    @Column(name = "GAME_ID", nullable = false)
    public Integer getGameId() {
        return this.gameId;
    }

    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    @Column(name = "PROJECT_ID", nullable = false)
    public Integer getProjectId() {
        return projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    @Column(name = "SUBJECT_ID", nullable = false)
    public Integer getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Mission mission = (Mission) o;

        if (!id.equals(mission.id)) return false;
        if (!name.equals(mission.name)) return false;
        if (!author.equals(mission.author)) return false;
        if (!dateIni.equals(mission.dateIni)) return false;
        if (observations != null ? !observations.equals(mission.observations) : mission.observations != null)
            return false;
        if (!gameId.equals(mission.gameId)) return false;
        if (!projectId.equals(mission.projectId)) return false;
        return subjectId.equals(mission.subjectId);

    }

    @Override
    public int hashCode() {
        int result = id.hashCode();
        result = 31 * result + name.hashCode();
        result = 31 * result + author.hashCode();
        result = 31 * result + dateIni.hashCode();
        result = 31 * result + (observations != null ? observations.hashCode() : 0);
        result = 31 * result + gameId.hashCode();
        result = 31 * result + projectId.hashCode();
        result = 31 * result + subjectId.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "Mission{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", author='" + author + '\'' +
                ", dateIni=" + dateIni +
                ", observations='" + observations + '\'' +
                ", gameId=" + gameId +
                ", projectId=" + projectId +
                ", subjectId=" + subjectId +
                '}';
    }
}
