package temperatus.model.pojo;
// Generated 09-feb-2016 22:15:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "POSITION", schema = "PUBLIC", catalog = "DATABASE", uniqueConstraints = @UniqueConstraint(columnNames = "PLACE"))
public class Position implements java.io.Serializable {

    private Integer id;
    private String place;
    private String picture;

    public Position() {
    }

    public Position(String place) {
        this.place = place;
    }

    public Position(String place, String picture) {
        this.place = place;
        this.picture = picture;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "PLACE", unique = true, nullable = false, length = 100)
    public String getPlace() {
        return this.place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    @Column(name = "PICTURE", length = 200)
    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    @Override
    public String toString() {
        return "Position{" +
                "place='" + place + '\'' +
                '}';
    }

}
