package temperatus.model.pojo;
// Generated 20-ene-2016 21:22:04 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Record generated by hbm2java
 */
@Entity
@Table(name = "RECORD", schema = "PUBLIC", catalog = "DATABASE")
public class Record implements java.io.Serializable {

	private Integer id;
	private Ibutton ibutton;
	private Position position;
	private Integer misionId;

	public Record() {
	}

	public Record(Ibutton ibutton, Position position, Integer misionId) {
		this.ibutton = ibutton;
		this.position = position;
		this.misionId = misionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IBUTTON_ID")
	public Ibutton getIbutton() {
		return this.ibutton;
	}

	public void setIbutton(Ibutton ibutton) {
		this.ibutton = ibutton;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POSITION_ID")
	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	@Column(name = "MISION_ID")
	public Integer getMisionId() {
		return this.misionId;
	}

	public void setMisionId(Integer misionId) {
		this.misionId = misionId;
	}

}
