package temperatus.model.pojo;
// Generated 08-dic-2015 14:25:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "TEST", schema = "PUBLIC", catalog = "DATABASE")
public class Test implements java.io.Serializable {

	private Integer id;
	private Experiment experiment;
	private Game game;
	private String name;
	private Date date;

	public Test() {
	}

	public Test(Experiment experiment, Game game, String name, Date date) {
		this.experiment = experiment;
		this.game = game;
		this.name = name;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXPERIMENT_ID")
	public Experiment getExperiment() {
		return this.experiment;
	}

	public void setExperiment(Experiment experiment) {
		this.experiment = experiment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GAME_ID")
	public Game getGame() {
		return this.game;
	}

	public void setGame(Game game) {
		this.game = game;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", length = 8)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Override
	public String toString() {
		return this.name;
	}
}
